botcard = '<b>📋 Bot name:</b> <code>{0}</code>\n<b>🗒 Bot description:</b> <code>{1}</code>\n<b>🛠 Last bot update:</b> <code>{2}</code>\n<b>⚙️ Runnable file:</b> <code>{3}</code>\n<b>👤️ Bot Creator:</b> {4}'
botcarddeploy = '<b>Bot deploy info:</b>\n\n<b>📋 Bot name:</b> <code>{0}</code>\n<b>🗒 Bot description:</b> <code>{1}</code>\n<b>🛠 Last bot update:</b> <code>{2}</code>\n<b>⚙️ Runnable file:</b> <code>{3}</code>\n<b>👤️ Bot Creator:</b> {4}'
runbtn = '▶️ Run'
stopbtn = '⏹ Stop'
stopped = '✅ Bot <b>{0}</b> was succesfully stopped\n\n🕑 Uptime: <code>{1}</code>'
permission = 'Permission denied'
botlist = '▶️️ <code>Bots running (all users):</code> <b>{0}</b>\n\n📂 <code>Bots aviable:</code> <b>{1}</b>'
started = '✅ Bot <b>{0}</b> was started with PID = {1}'
restarted = '✅ Bot <b>{0}</b> was relaunched with PID = {1}'
relaunch = '🔁 Relaunch'
goback = '↩️ Back to list'
request = 'User {0} want to deploy {1}'
running = '\n<b>🔌 Bot running on PID =</b> <code>{0}</code>\n<b>🕑 Uptime:</b> <code>{1}</code>'
rload = '🔄 Reload'
add_bot = '➕ Add'
add_help = 'If you want to add your bot to BotCPanel:\n\n1. Download <a href="https://cdn.discordapp.com/attachments/481928744005533718/481928951124721675/BOTINF_Tool.py">this</a> .py file and run it\n2. Fill in all inputs\n3. Put all your bot\'s files in the created directory\n4. Select all files in the directory and add them to a ZIP archive\n5. Rename the archive to "bot_NameOfYourBot»\n6. Message @Gr_Zd.'
back_to = '↩ Back to info'
bot_exit = 'Bot was closed with output: \n{0}\n\n🕑 Uptime: {1}'
botinfocard = 'Hello, this is BotCPanel!\n\nBotCPanel is a powerful bot hosting interface. With BotCPanel you can host bots written in any languages supported by Linux. BotCPanel advantages:\n1. VPN\n2. Personal Control Panel — you can quickly start, relaunch and stop your bots, and also check their uptime\n3. Pay only for the bot, not for hardware\n\n- Price: 0.5$/month per bot (Limited offer)'
files = 'Bot Files'
filestext = '📂 List of bot files:'